version: '2'


services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: dockerfiles/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: dockerfiles/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

 